version: 2.1

orbs:
  node: circleci/node@6.3.0
  azure-cli: circleci/azure-cli@1.2.2

jobs:
  build-node:
    executor: node/default # Use Default node executor, Change if it is required.
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  deploy: #TODO
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - azure-cli/install
      - run:
          name: Install SSH key
          command: echo -e "$SSH_PRIVATE_KEY | base64 --decode" > ~/ssh_key.pem
      - run:
          name: Set file permissions
          command: chmod 400 ~/ssh_key.pem
      - run:
          name: Deploy to Azure
          command: 
            ssh -o StrictHostKeyChecking=no -i ~/ssh_key.pem kyum@kyumericano.space 'cd portfolio && git pull && docker build -t portfolio . && docker stop portfolio && docker rm portfolio && docker run --name=portfolio -p 4000:15623 -d portfolio'

workflows:
  build:
    jobs:
      - build-node
      - deploy:
          requires:
            - build-node
          filters:
            branches:
              only:
                - main
